name: addon-patch

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # get full history so git log/describe work correctly
          fetch-tags: true       # ensure tags are available for describe/log ranges

      - name: Ensure tags present (safety)
        shell: bash
        run: |
          set -euo pipefail
          # In case the checkout action didn't fetch all tags for some reason
          git fetch --tags --force || true

      - name: Read current version
        id: cur
        shell: bash
        run: |
          set -euo pipefail
          CUR="$(sed -n 's/^version:[[:space:]]*//p' immich-drop/config.yaml | head -n1 | tr -d '\r')"
          if [ -z "${CUR}" ]; then
            echo "Could not read version from immich-drop/config.yaml" >&2
            exit 1
          fi
          BASE="$(echo "${CUR}" | sed -E 's/-[0-9]+$//')"
          SUFFIX="$(echo "${CUR}" | sed -nE 's/.*-([0-9]+)$/\1/p')"
          if [ -z "${SUFFIX}" ]; then
            NEW="${BASE}-1"
          else
            NEXT=$((SUFFIX+1))
            NEW="${BASE}-${NEXT}"
          fi
          echo "cur=${CUR}"   >> "$GITHUB_OUTPUT"
          echo "base=${BASE}" >> "$GITHUB_OUTPUT"
          echo "new=${NEW}"   >> "$GITHUB_OUTPUT"

      # Build and publish images BEFORE bump/tag/release to avoid HA pulling a non-existent tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        shell: bash
        env:
          GHCR_USER: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          FALLBACK_USER: ${{ github.actor }}
          FALLBACK_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          USERNAME="${GHCR_USER:-$FALLBACK_USER}"
          TOKEN="${GHCR_TOKEN:-$FALLBACK_TOKEN}"
          if [ -z "${TOKEN}" ]; then
            echo "No token available for GHCR login" >&2
            exit 1
          fi
          echo "${TOKEN}" | docker login ghcr.io -u "${USERNAME}" --password-stdin

      - name: Compute image names
        id: meta
        shell: bash
        env:
          NEW: ${{ steps.cur.outputs.new }}
        run: |
          set -euo pipefail
          OWNER="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          IMAGE_BASE="ghcr.io/${OWNER}/addon-immich-drop"
          echo "owner=${OWNER}" >> "$GITHUB_OUTPUT"
          echo "image_base=${IMAGE_BASE}" >> "$GITHUB_OUTPUT"
          echo "version=${NEW}" >> "$GITHUB_OUTPUT"

      - name: Build and push amd64
        uses: docker/build-push-action@v5
        with:
          context: ./immich-drop
          file: ./immich-drop/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.meta.outputs.image_base }}-amd64:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image_base }}-amd64:latest

      - name: Build and push aarch64 (arm64)
        uses: docker/build-push-action@v5
        with:
          context: ./immich-drop
          file: ./immich-drop/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ steps.meta.outputs.image_base }}-aarch64:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image_base }}-aarch64:latest

      - name: Build and push armv7
        uses: docker/build-push-action@v5
        with:
          context: ./immich-drop
          file: ./immich-drop/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.image_base }}-armv7:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image_base }}-armv7:latest

      - name: Create multi-arch manifest (version tag)
        shell: bash
        env:
          IMAGE_BASE: ${{ steps.meta.outputs.image_base }}
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          set -euo pipefail
          docker buildx imagetools create \
            -t "${IMAGE_BASE}:${VERSION}" \
            "${IMAGE_BASE}-amd64:${VERSION}" \
            "${IMAGE_BASE}-aarch64:${VERSION}" \
            "${IMAGE_BASE}-armv7:${VERSION}"

      - name: Create multi-arch manifest (latest)
        shell: bash
        env:
          IMAGE_BASE: ${{ steps.meta.outputs.image_base }}
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          set -euo pipefail
          if [ "${VERSION}" != "latest" ]; then
            docker buildx imagetools create \
              -t "${IMAGE_BASE}:latest" \
              "${IMAGE_BASE}-amd64:latest" \
              "${IMAGE_BASE}-aarch64:latest" \
              "${IMAGE_BASE}-armv7:latest"
          fi

      - name: Apply new version and pin Dockerfile UPSTREAM_REF
        shell: bash
        env:
          NEW: ${{ steps.cur.outputs.new }}
          BASE: ${{ steps.cur.outputs.base }}
        run: |
          set -euo pipefail
          sed -i -E "s|^(version:[[:space:]]*).*$|\1${NEW}|" immich-drop/config.yaml
          # Keep Dockerfile pinned to base upstream ref (without -X)
          sed -i -E "s|^ARG UPSTREAM_REF=.*$|ARG UPSTREAM_REF=${BASE}|" immich-drop/Dockerfile

      - name: Commit and push
        shell: bash
        env:
          
          NEW: ${{ steps.cur.outputs.new }}
          BASE: ${{ steps.cur.outputs.base }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add immich-drop/config.yaml immich-drop/Dockerfile
          git commit -m "chore(addon): bump add-on patch version to ${NEW} (base ${BASE})"
          git push

      - name: Create tag for release
        shell: bash
        env:
          NEW: ${{ steps.cur.outputs.new }}
        run: |
          set -euo pipefail
          if git ls-remote --tags origin "refs/tags/${NEW}" | grep -q "${NEW}"; then
            echo "Tag ${NEW} already exists, skipping"
          else
            git tag -a "${NEW}" -m "Immich Drop add-on ${NEW}"
            git push origin "${NEW}"
          fi

      - name: Compose release notes for GitHub
        id: rn
        shell: bash
        env:
          NEW: ${{ steps.cur.outputs.new }}
          BASE: ${{ steps.cur.outputs.base }}
          
        run: |
          set -euo pipefail
          {
            echo "Add-on patch release (base upstream ${BASE})"
            echo
          } > /tmp/release_notes.md

          format_range() {
            local range="$1"
            # pretty output: subject only (filter chore/docs)
            git log --no-color --pretty='%s' "${range}" \
            | while IFS= read -r subject; do
                # Exclude chore/* and docs/* (including chore(scope): or docs(scope):)
                first_word="${subject%% *}"
                if printf '%s' "${first_word}" | grep -Eq '^(chore|docs)(\(|:).*'; then
                  continue
                fi
                echo "- ${subject}"
              done
          }

          PREV="$(git describe --tags --abbrev=0 "${NEW}^" 2>/dev/null || true)"
          if [ -n "${PREV}" ]; then
            {
              echo "Changes since ${PREV}:"
              format_range "${PREV}..${NEW}"
              echo
            } >> /tmp/release_notes.md
          else
            {
              echo "Changes:"
              # Fallback: list up to 50 subjects reachable from NEW
              if git rev-parse --verify "${NEW}" &>/dev/null; then
                # Derive oldest commit among last 50 and build range oldest..NEW
                oldest="$(git rev-list -n 50 "${NEW}" | tail -n1 || true)"
                if [ -n "${oldest}" ]; then
                  format_range "${oldest}..${NEW}" || true
                else
                  # As ultimate fallback, just list latest 50 subjects
                  git log --no-color -n 50 --pretty='%s' "${NEW}" \
                  | grep -Ev '^(chore|docs)(\(|:).*' \
                  | sed 's/^/- /'
                fi
              fi
              echo
            } >> /tmp/release_notes.md
          fi

          echo "path=/tmp/release_notes.md" >> "$GITHUB_OUTPUT"


      - name: Update HA changelog (create if missing and prepend)
        shell: bash
        env:
          NEW: ${{ steps.cur.outputs.new }}
          BASE: ${{ steps.cur.outputs.base }}
          
        run: |
          set -euo pipefail
          mkdir -p immich-drop /tmp
          TARGET="immich-drop/CHANGELOG.md"
          TMP="/tmp/changelog_section.md"
          DATE="$(date -u +%Y-%m-%d)"

          {
            echo "## ${NEW} - ${DATE}"
            echo
          } > "${TMP}"

          if [ -f /tmp/release_notes.md ]; then
            cat /tmp/release_notes.md >> "${TMP}"
            echo >> "${TMP}"
          fi

          if [ -f "${TARGET}" ]; then
            cat "${TARGET}" >> "${TMP}"
          fi

          mv "${TMP}" "${TARGET}"

      - name: Commit changelog
        shell: bash
        env:
          NEW: ${{ steps.cur.outputs.new }}
          BASE: ${{ steps.cur.outputs.base }}
          
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          TARGET="immich-drop/CHANGELOG.md"
          if [ ! -f "${TARGET}" ]; then
            # Defensive fallback to avoid pathspec error if previous step was skipped
            mkdir -p immich-drop
            DATE="$(date -u +%Y-%m-%d)"
            {
              echo "## ${NEW} - ${DATE}"
              echo
            } > "${TARGET}"
            if [ -f /tmp/release_notes.md ]; then
              cat /tmp/release_notes.md >> "${TARGET}"
              echo >> "${TARGET}"
            fi
          fi

          # Only commit if file is new or changed
          if [ -z "$(git status --porcelain -- ${TARGET} || true)" ]; then
            echo "No changelog changes to commit"
            exit 0
          fi

          git add "${TARGET}"
          git commit -m "docs(changelog): add ${NEW}"
          git push

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.cur.outputs.new }}
          name: ${{ steps.cur.outputs.new }}
          body_path: ${{ steps.rn.outputs.path }}
          draft: false
          prerelease: false
          make_latest: true